version: "2"

services:

  atelier:
    build: .
    networks:
      atelier_net:
          ipv4_address: 192.168.1.1
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    container_name: atelier

networks:

  atelier_net:
      ipam:
          driver: default
          config:
              - subnet: 192.168.1.0/24
                gateway:  192.168.1.254

