version: "2"

services:

  compta:
    build: .
    networks:
      compta_net:
          ipv4_address: 192.168.4.1
    container_name: compta

networks:

  compta_net:
      ipam:
          driver: default
          config:
              - subnet: 192.168.4.0/24
                gateway:  192.168.4.254

