version: "2"

services:

  secretariat:
    build: .
    networks:
      secretariat_net:
          ipv4_address: 192.168.5.1
    container_name: secretariat

networks:

  secretariat_net:
      ipam:
          driver: default
          config:
              - subnet: 192.168.5.0/24
                gateway:  192.168.5.254

