version: "2"

services:

  direction:
    build: .
    networks:
      direction_net:
          ipv4_address: 192.168.2.1
    container_name: direction

networks:

  direction_net:
      ipam:
          driver: default
          config:
              - subnet: 192.168.2.0/24
                gateway:  192.168.2.254

